### ISSUE TITLE
not working on non-www pages

### ISSUE THREAD

**Issue by cribsb** [gblazex/smoothscroll#108]
Hello,

I'm a webdeveloper and when I open pages through file://C:/blablabla the smoothscroll doenst work.

**Comment by DenVdmj** [comment]
Yes, it’s annoying problem to me too. I’m forced to use the edited local version with <all_urls> in permissions. Please fix it, if it’s possible.

**Comment by galambalazs** [comment]
It's certainly possible I'm just not sure if adding "file:///" disables the extension because the permissions change. https://developer.chrome.com/extensions/permission_warnings

In theory it shouldn't because we're already granted all hosts permission, but I never saw how an added protocol affects this.

So we'd have to make sure not to mess with all the other 150,000 users' experience. :)

**Comment by caselmer** [comment]
Hello, 
I also would like to use scroll with middle mouse button on pages which reside on hdd, (linux). Especially I need it for file:///usr/share/doc/openjdk-doc/api/index.html. 

From previous comments I understand, it must be possible somehow.

In .config/chromium/Default/Extensions/nbokbjkabcmbfdlbddjidfmibcpneigj/1.6.1_0/manifest.json I added <all_urls> to permissions, or rather I substituted. 
I also fiddled around with 'content_scripts ... matches'. But it did not work.

Could you please show me _exactly_ how to do it? 
Thank you.

**Comment by galambalazs** [comment]
There's an option on chrome://extensions page to enable it to run on local files.

**Comment by caselmer** [comment]
I don't see such an option, neither in chrome://extensions, nor in 
chrome-extension://nbokbjkabcmbfdlbddjidfmibcpneigj/pages/options.html. 

I see that my extension 'uBlock Origin' has a checkbox "Zugriff auf Datei-URLs zulassen /   Allow access to file URLs", but SmoothScroll does not have such a checkbox. 

Version:
Chromium  56.0.2924.76 built on Debian 9.0
SmoothScroll 1.6.1
