### ISSUE TITLE
Horizontal scrolling with shift doesn't work

### ISSUE THREAD

**Issue by Yanpas** [gblazex/smoothscroll#175]
By default holding shift in chrome switches scroll direction to horizontal

**Comment by gblazex** [comment]
works for me

**Comment by Yanpas** [comment]
Tried to enable/disable keyboard. I'm using linux

**Comment by gblazex** [comment]
unfortunately I don't have linux to test on, Mac & Windows works for me

**Comment by gblazex** [comment]
fixed

**Comment by geekley** [comment]
@gblazex Shift+scroll is not working for me.
Tested in Windows, Opera, v1.6.31, https://beetleinc.co.za/test-page-scroll/
Also tested in Windows, Brave, v1.6.32

Also, (I dunno if it's by design but) when there's a scroll area inside another, only the inner one under the mouse scrolls. This behavior is different from the browser. When it cant go further but the parent scroll area still can and you insist on scrolling, the browser scrolls the outer area even with the mouse in the inner area. I just wanted to mention that the behavior is different, I don't know if it's better this way.
