### ISSUE TITLE
Since Chrome 73.0.3683.75 Update, middle mouse scrolling doesn't work properly

### ISSUE THREAD

**Issue by iori3000** [gblazex/smoothscroll#182]
Since Chrome 73.0.3683.75 Update
middle mouse scrolling doesn't work properly

**Comment by stanczew** [comment]
Probably due to: https://developers.google.com/web/updates/2019/02/scrolling-intervention

It looks like SmoothScroll tries do do its thing (i.e. scroll a defined amount), but gets "bounced back" and then only standard Chromium scrolling is applied.
Plus I can see the "[Intervention] Unable to preventDefault …" log every time I use the scroll wheel with the extension enabled.

**Comment by artik** [comment]
Affected also, using Chrome Linux. I was about to report it when I sew Iori3000 did. Hope will be solved :)

**Comment by stanczew** [comment]
The fix suggested in the article works:
```
 function addEvent(type, fn) {
-    window.addEventListener(type, fn, false);
+    window.addEventListener(type, fn, {passive: false});
 }
```
There is already a pull request with this change: #164

**Comment by gblazex** [comment]
fixed in latest version
